# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: 
      - master
      - feature-123
      - devlop 
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn build 
    - run: yarn  test --watchAll=false
    - name: Deploy to GH Pages
      run: |
        git config --global user.email ${{secrets.GIT_EMAIL}}
        git config --global user.name ${{secrets.USERNAME}}
        git remote set-url origin https://${{secrets.SECRET_TOKEN}}@github.com/AhmedELShafaie/calculator.git
        npm run deploy
